from .block_noise_node import (
    NODE_CLASS_MAPPINGS as BLOCK_NOISE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BLOCK_NOISE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .no_noise_ksampler_node import (
    NODE_CLASS_MAPPINGS as NO_NOISE_KSAMPLER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NO_NOISE_KSAMPLER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .wildcards_node import (
    NODE_CLASS_MAPPINGS as WILDCARDS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WILDCARDS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .trigger_tag_replace_node import (
    NODE_CLASS_MAPPINGS as TRIGGER_TAG_REPLACE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TRIGGER_TAG_REPLACE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lora_loader_node import (
    NODE_CLASS_MAPPINGS as LORA_LOADER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LORA_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
)
from .resolution_node import (
    NODE_CLASS_MAPPINGS as RESOLUTION_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RESOLUTION_NODE_DISPLAY_NAME_MAPPINGS,
)
from .lm_studio_llm_node import (
    NODE_CLASS_MAPPINGS as LM_STUDIO_LLM_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LM_STUDIO_LLM_NODE_DISPLAY_NAME_MAPPINGS,
)
from .mcp_skills_node import (
    NODE_CLASS_MAPPINGS as MCP_SKILLS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MCP_SKILLS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .wdv3_tagger_node import (
    NODE_CLASS_MAPPINGS as WDV3_TAGGER_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WDV3_TAGGER_NODE_DISPLAY_NAME_MAPPINGS,
)

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(WILDCARDS_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BLOCK_NOISE_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(NO_NOISE_KSAMPLER_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(TRIGGER_TAG_REPLACE_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LORA_LOADER_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(RESOLUTION_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(LM_STUDIO_LLM_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MCP_SKILLS_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(WDV3_TAGGER_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(WILDCARDS_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BLOCK_NOISE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(NO_NOISE_KSAMPLER_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TRIGGER_TAG_REPLACE_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LORA_LOADER_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(RESOLUTION_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(LM_STUDIO_LLM_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MCP_SKILLS_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WDV3_TAGGER_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
